theme: jekyll-theme-minimal

url: "https://briancalbrecht.github.io" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Google Analytics
google_analytics: UA—31017694-4