---
title: ECON2105-05 Principles of Macroeconomics
author: Brian Albrecht
date:
output:
  bookdown::pdf_document2:
    citation_package: natbib
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
    template: https://briancalbrecht.github.io/defaults/svm-latex-syllabus.tex
    toc: no
  bookdown::gitbook:
  bookdown::html_document2:
    toc: yes
  config:
    toc:
      collapse: subsubsection
      scroll_highlight: yes
      before: null
      after: null
    toolbar:
      position: fixed
    edit : null
    download: null
    search: yes
    fontsettings:
      theme: white
      family: sans
      size: 2
    sharing:
      facebook: no
      twitter: no
      google: no
      linkedin: no
      weibo: no
      instapaper: no
      vk: no
      all: ['facebook', 'google', 'twitter', 'linkedin', 'weibo', 'instapaper']
email: balbrec4@kennesaw.edu
fontfamily: mathpazo
fontsize: 11pt
geometry: margin=1in
header-includes: \linespread{1.05}
office: Burruss Building 359
officehours: Th 2-4, or by appointment
classroom: Social Sciences Bldg 2034	
classhours: Tu-Th 9:30 am - 10:45 am
web: d2l.kennesaw.edu
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, dev='pdf')
mon <- as.Date("2021-08-16")
# fri <- as.Date("2016-01-08")
advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Week ",zadv,sep='',", ", tmon," - ",tfri)
 return(tmp)
}
library(RefManageR)
library(knitcitations)
library(rcrossref)
```

# tl;dr
The course has three exams (9/23, 10/28, 12/9), which are based on the lectures and make up 90% of your grade. If you want a course made up of busy work each week, drop this one. Come to lecture and office hours to get the most out of this course.


# Course Description and Objectives {-}

This course is an introduction to the formal study of macroeconomics.

Macroeconomics involves the study of the economy as a whole. Topics that will be covered include national
income determination, the general price level, interest rates, unemployment, and fiscal and monetary policies.
The emphasis will be on genuine understanding of the material, and not on "memorization".

To say that the economy is immensely complex is an understatement.  Indeed, you may be skeptical that we can say anything meaningful about how it actually operates.  This belief, while common, is mistaken.
There are certain universal traits of human nature that yield principles capable of explaining the economic
forces that shape the world around us. Upon successfully completing this course, you will be conversant in the basic principles of macroeconomics and prepared for more advanced coursework on this subject.

 



## Textbook 
Case/Fair/Oster, Principles of Macroeconomics, 13th Edition. 2020.

Please note that **exams will be based on the lectures.** The textbook is only meant to supplement the lectures. Other supplemental readings/podcasts/videos will be posted.

## Day One Access {-}

ECON2105 is part of a textbook program called Day One Access. The week before
classes begin, you should receive an e-mail from KSU University Stores with instructions on how
to access the course content (please check your junk folder if not in your inbox). The purpose
of Day One Access is to make sure that you have access to the digital course materials on or
before the first day of class at a highly competitive rate. Everyone enrolled in the course will
automatically have access to the digital course materials through drop/add. Those who have
not opted-out or dropped the class by drop/add, will receive a charge from the bookstore on
their OwlExpress student account the following week. 

You have the ability to Opt-Out, via the link in the email sent to you by University Stores. Once
you opt out, you will immediately receive a confirmation email. If you do not receive this email,
you did not successfully opt out. If, after multiple tries, you are unable to successfully opt out
via the link, please email dayone@kennesaw.edu prior to the opt-out deadline and request to
be manually opted out. You must include your name, student ID number, and the course info.
Emails sent after the deadline will not be acknowledged.  

You should also login and register your materials via the link during the first week of class. If
you do not do register by this date, you may temporarily lose access and an access code may
be requested despite not having opted out. If this happens, please
email dayone@kennesaw.edu. (DO NOT purchase an access code if this happens, as you will
not be refunded. Please wait for a response to your email.) 

If you would like to know more about Day One Access, please
visit https://ksustore.kennesaw.edu/textbooks/day_one_access.php.


## Course Prerequisites: 
Business Majors: MATH 1111  or higher; Non-business Majors: MATH 1101 or higher


## Course Withdrawal Date and Policy: 
Last day to withdraw without academic penalty is Thursday, 10/21/2021.
Students withdrawing after this date will receive a WF. Students who wish to withdraw with a grade of “W”
must do so formally through the Registrar’s Office on or before 10/21. All withdrawals must be processed
officially through the Office of The Registrar by the student.

## Make-Up Exam Policy: 
**No make-up exams** or assignments will be given during the semester. It is the student’s responsibility to check the course calendar and announcements in D2L.

## Attendance Policy: 
Class success and learning depends on your interaction,
including reading all materials and being alert for announcements. You are expected to check D2L
on a daily basis and if not certainly every week. Posts made to the Class Café by your professor are
required reading and may contain important announcements. In addition, all items in the Learning
Modules are required readings. Students should realize that it is highly unlikely that a student will
earn a passing grade if he/she does not actively participate in this class each week. Further, office
hours will not be dedicated to correct deficiencies induced by lack of participation. 

# Grading Policy: 
Grading for this course will be based on three (3) exams and homework. Each exam will be worth 30% of your final grade. The remaining 10% of your grade will be based on homework (see the handout). There will be NO
MAKE-UP EXAMS. If you miss an exam, the next exam will count as double. If you miss two consecutive exams,
you will receive an ’F’. **Please note that this is NOT an invitation to skip an exam.** If you miss an exam,
you must have a satisfactory excuse. Examples of satisfactory excuses include a documented illness (i.e. one that
requires a note from a doctor), funeral services, military service, religious observances, and university-sponsored
activities. In the event that an absence is known about in advance, I will make arrangements with the student to
take the exam at an alternate time.


## EXAMS:
- There will be two midterms and a final exam during the semester.
- The midterms and final exams will be **in person**. No make-up will be given for any of
the exams.
- The first midterm exam is tentatively scheduled for **Thursday, September 23, 2021**.
- The second midterm exam is tentatively scheduled for **Thursday, October 28, 2021**.
- The date for the final exam is **Thursday, December 9, 2021**.


## Overall Class Grade

- - Overall class grades will be rounded to the nearest number (e.g. 89.33 will be rounded to 89, 89.67 to
90, or 59.72 to 60 etc.)

- The grading scale will be as follows: 100-90 A, 80-89 B, 70-79 C, 60-69 D, 59-0 F

Incomplete Grades: Incompletes are awarded for non-academic reasons at the instructor’s discretion, and
not at students’ discretion.

Note: For all other questions related to grading policy, see the KSU 2021-2022 undergraduate catalogue. 
\newpage

## Tentative Schedule {-}
The material covered will include, but not be limited to:

• Material Covered Before Exam 1

  – Microeconomics Review
  
  – Introduction to Macroeconomics

• Material Covered Before Exam 2

  – Consumption, Savings, and Investment
  
  – Economic Growth

• Material Covered Before Exam 3

  – Money, Banks, and Financial Markets
  
  – Monetary Policy
  
  – Fiscal Policy

On October 7th, we will have guest lecture by Will Luther (Florida Atlantic University economist https://www.williamjluther.com/) titled "What is Bitcoin really worth?". The lecture will be open to the public and part of a Bagwell Center event.

**Note**: Changes to this course outline and schedule, if needed, will be announced through the Class Cafe
discussion, via D2L email, or both. It is the responsibility of students to stay aware of changes that may occur
during the semester.

**One Final Note**: You are undoubtedly tired of hearing this, but you are here to get an education, not merely
to pass classes. The amount of effort that you put in to this class is strongly correlated with the final result. You can view this course as a learning experience or as a grind. Ultimately, the choice is yours. However, choosing to
view the courses you take as a learning experience rather than a grind will likely result in better performance and
a much more enjoyable college experience. Never underestimate the value of your education.

# Course Policies

**Instructor Contact Information:** If I am online in D2L and available, you are welcome to initiate a chat. If I'm
online, click the "Send Chat Invitation" button. If it is not a convenient time to engage in a conversation, I will
decline the invitation - please follow-up by sending me a D2L e-mail message.

During D2L maintenance, or if you are unable to access it – You may contact me through campus e-mail at
balbrec4@kennesaw.edu

**Instructor Response:** Questions of a general nature should be asked in the Class Caff discussion.
Students are encouraged to answer and help other students. 

Specific questions for the instructor should be emailed through D2L. Responses will be provided within 24 hours during
the business week. Questions received on weekends will be answered at first opportunity on Monday. Feedback and
scores on graded work are provided within one week of the assignment due date. 

**Late Assignments:** Late assignments will NOT be accepted. Check the calendar for the due dates. In the event of a
server failure or natural occurrences, students are required to submit assignments through campus e-mail (to:
balbrec4@kennesaw.edu) PRIOR to the expiration time of the assignment. 

**Important:** DO NOT WAIT until a few minutes before an assignment is due. Taking an Online Quiz, uploading your Short
Essay document, or posting your Online Discussion Question response will take time, and will depend on file size, the
processing speed of your computer, the speed of your internet connection, and the load on the server. Assignment
submission times are recorded

**Important:** D2L has scheduled maintenance times. These dates/times are determined in advance and displayed when
you log into VISTA. You are responsible for noting these and adjusting your schedule accordingly. Late assignments will
not be accepted because of D2L inaccessibility due to scheduled maintenance. 



# USGS COVID-19 Syllabus Statements


## Course Delivery
KSU may shift the method of course delivery at any time during the semester in compliance with University System of Georgia health and safety guidelines.  In this case, alternate teaching modalities that may be adopted include hyflex, hybrid, synchronous online, or asynchronous online instruction.



## Staying Home When Sick
If you are feeling ill, please stay home and contact your health professional.  In addition, please email your instructor to say you are missing class due to illness. Signs of COVID-19 illness include, but are not limited to, the following:  

-	Cough
-	Fever of 100.4 or higher
-	Runny nose or new sinus congestion
-	Shortness of breath or difficulty breathing
-	Chills
-	Sore Throat
-	New loss of taste and/or smell 


COVID-19 vaccines are a critical tool in “Protecting the Nest.” If you have not already, you are strongly encouraged to get vaccinated immediately to advance the health and safety of our campus community.  As an enrolled KSU student, you are eligible to receive the vaccine on campus. Please call (470) 578-6644 to schedule your vaccination appointment or you may walk into one of our student health clinics. 

For more information regarding COVID-19 (including testing, vaccines, extended illness procedures and accommodations), see KSU’s official Covid-19 website. 

## Face Coverings

Based on guidance from the University System of Georgia (USG), all vaccinated and unvaccinated individuals are encouraged to wear a face covering while inside campus facilities. Unvaccinated individuals are also strongly encouraged to continue to socially distance while inside campus facilities, when possible.

# University Policies

## Academic Integrity Statement
Every KSU student is responsible for upholding the provisions of the Student Code of Conduct, as published in
the Undergraduate and Graduate Catalogs. Section 5c of the Student Code of Conduct addresses the University
’s policy on academic honesty, including provisions regarding plagiarism and cheating, unauthorized access
to university materials, misrepresentation/falsification of university records or academic work, malicious
removal, retention, or destruction of library materials, malicious/intentional misuse of computer facilities and/or
services, and misuse of student identification cards. Incidents of alleged academic misconduct will be
handled through the established procedures of the Department of Student Conduct and Academic
Integrity(SCAI, which includes either an “informal” resolution by a faculty member, resulting in a grade
adjustment, or a formal hearing procedure, which may subject a student to the Code of Conduct’s
minimum one semester suspension requirement. See also https://web.kennesaw.edu/scai/content/
ksu-student-code-conduct

## Disruptive Behavior
Belligerent, abusive, profane, threatening and/or inappropriate behavior on the part of students is a violation of
the KSU Student Code of Conduct. According to university policy regarding disruptive behavior, students who
are found in violation of the Code of Conduct may be subject to immediate dismissal from the university. Also,
those violations, which may constitute misdemeanor or felony violations of state or federal law, may also be
subject to criminal action beyond the university disciplinary process. 

## Special Needs & Accommodations
Kennesaw State University provides program accessibility and reasonable accommodations for persons
defined as disabled under Section 504 of the Rehabilitation Act of 1973 and the Americans with
Disabilities Act of 1990. Students with disabilities who require accommodations (academic adjustments and/
or auxiliary aids or services) for this course must contact the Office for Disabled Student Support Services,
ADA Compliance Officer for Students, at 770-423-6443 (V) or 770-423-6480 (TDD). Please do not request
accommodations directly from the professor or instructor without a letter of accommodation from the
Office for Disabled Student Support Services. For additional information, please visit: http://www.kennesaw.edu/stu_dev/dsss/dsss.html.
## Student Code of Conduct – Strictly Enforced

### Plagiarism and Cheating
No student shall receive, attempt to receive, knowingly give or attempt to give unau-thorized assistance in
the preparation of any work required to be submitted for credit as part of a course (including exami¬nations,
laboratory reports, essays, themes, term papers, etc.). When direct quotations are used, they should be
indicated, and when the ideas, theories, data, figures, graphs, programs, electronic based infor¬mation or
illustrations of someone other than the student are incorporated into a paper or used in a project, they should
be duly acknowledged.

### Translated Examples of Academic Dishonesty Covered Under the Student Code of Conduct
All graded work is to be performed by the individual, unless otherwise specified as a group project. Work
submitted that is not representative of individual effort is prohibited and considered a violation of the code of
conduct. This includes the shared use of electronic files. Use of any electronic file not specifically made
available to the individual in the currently enrolled course is prohibited and considered a violation of the
code of conduct. In a credit-generating course where class attendance/participation is tied directly to a
grading structure or point system, misrepresentation of attendance/participation is considered a
violation of the code of conduct. On-line examinations are subject to the same classroom setting
protocols as traditional examinations. 