---
title: 
author:
date:
output:
  bookdown::gitbook:
  bookdown::pdf_document2:
    citation_package: natbib
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
    template: C:/Users/Brian/Documents/briancalbrecht.github.io/defaults/svm-latex-syllabus.tex
    toc: no
  bookdown::html_document2:
    toc: yes
  config:
    toc:
      collapse: subsubsection
      scroll_highlight: yes
      before: null
      after: null
    toolbar:
      position: fixed
    edit : null
    download: null
    search: yes
    fontsettings:
      theme: white
      family: sans
      size: 2
    sharing:
      facebook: no
      twitter: no
      google: no
      linkedin: no
      weibo: no
      instapaper: no
      vk: no
      all: ['facebook', 'google', 'twitter', 'linkedin', 'weibo', 'instapaper']
email: mail@briancalbrecht.com
fontfamily: mathpazo
fontsize: 11pt
geometry: margin=1in
header-includes: \linespread{1.05}
office: 
officehours: 
classroom: 
classhours: 
web: briancalbrecht.com/pricetheory
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=FALSE, dev='pdf')
mon <- as.Date("2019-09-9")
# fri <- as.Date("2016-01-08")
advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Week ",zadv,sep='',", ", tmon," - ",tfri)
 return(tmp)
}
library(RefManageR)
library(knitcitations)
library(rcrossref)
bib <- ReadBib("C:/Users/brian/Documents/githubprivate/defaults/library.bib")
myopts <- BibOptions(bib.style = "authoryear", style="latex", first.inits=FALSE, max.names = 20)
```

# Chicago Price Theory Reading Group {-}

This virtual discussion group is meant for graduate students and professors across the world to work together to better understand Chicago price theory, through the new textbook.

All discussions will take place via Google Meet. Please use [this link](https://meet.google.com/ngm-ksav-vky).

## Time (Tentative) {-}

Wednesday 2-3PM Central (if that does not work, please message me with a better time)

## Objectives {-}

1. Sharpen price theory skills

2. Find ways to incorporate price theory into research

## Discussion Structure (Tentative)  {-}

Each week's discussion will start and end on time. 

We will be going through the textbook, page by page. I as discussion leader will ask, "are there any questions on page X?,,, Are there any questions on page X+1?"

I am also consider the idea of people presenting new simple, price theory models outside of the reading. For the first 10 minutes or so, one participant will explain either 1) a model they are working on or 2) a model from another paper. This is meant to help bridge the gap between the textbook treatment and the ultimate use of price theory as a tool for understanding.

Any other suggestions are appreciated!
\newpage

## Schedule (Tentative) {-}


### `r advdate(mon, 1)`: Discussion Group Planning {-}


### `r advdate(mon, 2)`: Introduction and Chapter 1 and 2: Utility Max{-}


### `r advdate(mon, 3)`: Chapters 2 and 3: Cost Min and Relating Marshall/Hicks {-}




### `r advdate(mon, 4)`: Chapters 4 and 5: Price Indices and Nudges {-}




### `r advdate(mon, 5)`: Chapter 6 and 7: Short vs Long Run Demand, Discrete Choice, Product Quality {-}



### `r advdate(mon, 6)`: Chapter 8: Location Choice, Equilibrium  {-}
### `r advdate(mon, 7)`: Chapter 9: Learning by Doing {-}
### `r advdate(mon, 8)`: Chapter 10: Production, Profits, and Factor Demand {-}

### `r advdate(mon, 9)`: Chapters 11 and 12: Industry Model, Prohibition {-}

### `r advdate(mon, 10)`: Chapters 13 and 14: The Core, Multi-factor Model {-}

### `r advdate(mon, 11)`: Chapter 15: Durable Production Factors {-}

### `r advdate(mon, 12)`: No Reading Group: Thanksgiving {-}

### `r advdate(mon, 13)`: Chapters 16 and 17: Capital Accumulation, Investment from Planning Perspective {-}

### `r advdate(mon, 14)`: Chapter 18: Applied Factor Supply and Demand I {-} 

### `r advdate(mon, 15)`: Chapter 19: Applied Factor Supply and Demand II {-}

